stages:
  - dependencies
  - lint
  - deploy

install_dependencies:
  image: node:16-alpine
  stage: dependencies
  script:
    - cd client-web
    - npm install
  only:
    - main
  cache:
    key:
      files:
        - client-web/package-lock.json
    paths:
      - client-web/node_modules

lint:
  image: node:16-alpine
  stage: lint
  script:
    - cd client-web
    - npm link @angular/cli@13.1.2
    - ng lint
  cache:
    key:
      files:
        - client-web/package-lock.json
    paths:
      - client-web/node_modules/
    policy: pull

pages:
  image: node:16-alpine
  stage: deploy
  cache:
    paths:
      - client-web/node_modules/
  script:
    - cd client-web
    - npm install -g @angular/cli@13.1.2
    - npm install
    - ng build
    - cd ..
    - mkdir -p public
    - mv /client-web/public/* public/
  artifacts:
    paths:
      - public
  only:
    - main
