stages:
  - dependencies
  - lint
  - build
  - deploy

variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR/client-web'
  OUTPUT_PATH: '$CI_PROJECT_DIR/client-web/public/browser' # Angular output path. Defined in angular.json
  API_PATH: '' # empty for now


install_dependencies:
  image: node:22-alpine
  stage: dependencies
  script:
    - cd client-web
    - npm install
  only:
    - main
  cache:
    key:
      files:
        - client-web/package-lock.json
    paths:
      - client-web/node_modules

lint:
  image: node:22-alpine
  stage: lint
  script:
    - cd client-web
    - npx ng lint
  cache:
    key:
      files:
        - client-web/package-lock.json
    paths:
      - client-web/node_modules/
    policy: pull
  only:
    - main

build:
  image: node:22-alpine
  stage: build
  script:
    - cd client-web
    - npx ng build --configuration production
  cache:
    key:
      files:
        - client-web/package-lock.json
    paths:
      - client-web/node_modules/
    policy: pull
  artifacts:
    paths:
      - client-web/public/browser
  only:
    - main

deploy:
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "App deployed successfully."
  only:
    - main

deploy_api:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  script:
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    - apt-get update -qq && apt-get install -y -qq maven
    - cd api
    - mvn azure-functions:deploy -DskipTests
  only:
    - main
